------------------------------------------------------------
-- languages.lua
-- SmartSheep localization system (translations + helpers)
------------------------------------------------------------

local M = {}

-- Supported languages (keys must exist in M.text)
M.supported = { "en", "es", "fr", "de", "zh", "ja", "ko" }

-- Default language
M.current = "en"

------------------------------------------------------------
-- Translations
------------------------------------------------------------
M.text = {

    ----------------------------------------------------------------
    -- English
    ----------------------------------------------------------------
    en = {
        home = "Home",
        edit = "Edit",
        greeting = "Hello",
                game_catch = "Catch",
        game_catch_desc = "Catch the words",

        game_match = "Match",
        game_match_desc = "Drag words to spot",
        word_card_game = "Word Card Game",
        drag_words_instruction = "Drag each word card into the correct spot.",
        screen_count = "Screen %d of %d",
        no_words_saved = "Add some words first, then preview the game.",

        game_order = "Order",
        game_order_desc = "Connect the order",
        line_match_game = "Line Match Game",
        draw_line_instruction = "Draw a line from each word to its matching spot.",
        player = "Player",
        menu = "Menu",
        choose_a_game = "Choose a Game",
        log_in = "Log In",
        exit = "Exit",
        language = "Language",
        success = "Success",
        error = "Error",
        saving = "Saving...",
        save_failed = "Save failed",
        updated = "Updated",
        updating = "Updating...",
        seed_error = "Seed error",
        no_passages_found = "No passages found",
        creating_new_passage = "Creating new passage...",
        select_passage  = "Select Passage to Edit",
        tutorial_welcome_title = "Welcome!",
        tutorial_welcome_text = "Create fun Bible games for your students. They will play what you build.",
        tutorial_students_play_title = "Students Play",
        tutorial_students_play_text = "Your classes and levels become games for students.",
        tutorial_student_app_text = "Your students install the SmartSheep student app. It is free and has NO ads.",
        tutorial_add_class_title = "Add Class",
        tutorial_add_class_text = "Tap Add Class below to create your first class.",
        tutorial_class_details_title = "Class Details",
        tutorial_class_details_text = "Students will access your game with the generated ID.",
        tutorial_students_join_title = "Students Join",
        tutorial_students_join_text = "In the SmartSheep app, students will enter your Class ID.",
        tutorial_students_replay_text = "After joining, students will see your class in their app to play again and again.",
        tutorial_tutorials_title = "Tutorials",
        tutorial_tutorials_text = "Review the tutorials under the ? in the upper right on each screen.",
        tutorial_catch_words = "Catch the words!",
        tutorial_next = "Next ›",

        tutorial_class_settings_title = "Class Settings",
        tutorial_class_settings_text = "This is where you can update your class.",
        tutorial_change_class_name_title = "Change Class Name",
        tutorial_change_class_name_text = "Tap the Class Name box to rename your class.",
        tutorial_publish_class_title = "Publish Class",
        tutorial_publish_class_text = "Tap Published when your class is ready for students.",
        tutorial_save_changes_title = "Save Changes",
        tutorial_save_changes_text = "Tap Save to update your class name and publish setting.",
        tutorial_add_level_title = "Add a Level",
        tutorial_add_level_text = "Tap Add Level to create game levels for this class.",
        tutorial_class_name_label = "Class Name:",
        tutorial_sample_class_name = "Sunday School",
        tutorial_draft = "Draft",
        tutorial_published = "Published",
        tutorial_add_level_button = "➕ Add Level",

        tutorial_level_title_title = "Level Title",
        tutorial_level_title_text = "Give your level a title. Students will see this when choosing what to play.",
        tutorial_choose_theme_title = "Choose Theme",
        tutorial_choose_theme_text = "Pick a theme to change how the game looks.",
        tutorial_words_to_remember_title = "Words to Remember",
        tutorial_words_to_remember_text = "Add a memory verse or words you want students to remember.",
        tutorial_success_message_title = "Success Message",
        tutorial_success_message_text = "Add encouragement, verse notes, next class plans, or reminders.",
        tutorial_preview_game_title = "Preview Game",
        tutorial_preview_game_text = "Tap Preview Game to test the game before students play.",
        tutorial_preview_success_title = "Preview Success",
        tutorial_preview_success_text = "Tap Preview Success to see the message students get after finishing.",
        tutorial_sample_level_name = "Early Learners - Psalm 118:1",
        tutorial_sample_theme = "Undersea ▼",
        tutorial_sample_words = "God is good",
        tutorial_sample_success_message = "Great job! Remember this verse this week.",
        preview_game    = "Preview Game",
        preview_success = "Preview Success",
        edit_level = "Edit Level",
        save_first = "Save First",
        theme_helper = "Choose a theme for this level.",
        add_words_to_remember = "Add Words to Remember",
        add_success_message = "Add Success Message",
        new_code = "New Code",
        published = "Published",
        draft = "Draft",
        loading_classes = "Loading classes...",
        share_with_students = "Share this with your students.",
        enter_level_name = "Enter a level name",
        save = "Save",
        tap_theme_then_done = "Tap a theme, then Done",
        selected_theme = "Selected",
        done = "Done",
        save_to_preview_edits = "Save to preview edits",
        missing_user_class = "Missing user or class.",
        please_enter_level_name = "Please enter a level name.",
        creating_new_level = "Creating new level...",
        hint_instruction = "Move basket to catch words in order.",
        hint_remove_last_word = "Catch %s to erase the last word.",
        hint_tap_panel = "Tap this panel to view the verse.",
        missing_level_id = "Missing level id.",
        please_select_level_first = "Please select a level first.",
        deleting = "Deleting",
        delete_failed = "Delete failed.",
        needs_text = "Needs Text",
        delete_level = "Delete Level?",
        delete_level_msg = "This will delete this level.",
        delete = "Delete",
        dont_see_level = "Don’t see the level you want? Add one below.",
        add_level = "Add Level",
        manage = "Manage",
        no_success_messages_found = "No success messages found",
        loaded = "Loaded",
        title_topic_or_passage = "Title, Topic or Passage",
        add_new = "Add New",
        select_class = "Select Your Class",
        select_label = "Select Class",
        no_class_selected = "No Class Selected",
        no_classes_available = "No classes available",
        add_class = "Add Class",
        save_class = "Save Class",
        load_class = "Loading Class",
        load_failed = "Load failed",
        load_error = "Load error",
        loading = "Loading...",
        please_select_class = "Please select a class before continuing.",
        ok = "OK",
        class_id = "Class ID",
        class_name = "Enter Class Name",
        error_missing = "Please enter both class ID and class name.",
        success_added = "Class added!",
        error_connection = "Could not connect to server. Please try again later.",
        next = "Next",
        back = "Back",
        select_language = "Select Language",
        language_updated = "Language Updated",
        restart_notice = "The change will apply immediately.",
        play_game = "Play Game",
        create = "Create",
        enter_code = "Enter Code",
        hint = "Hint",
        please_enter_class_code = "Please enter a class code.",
        please_login = "Please log in.",
        please_login_or_enter_class_code = "Please log in or enter a class code.",
        welcome = "Welcome",
        welcome_to = "Welcome to",
        theme = "Theme",
        about    = "About",
        support  = "Support",
        settings = "Settings",

        optional_add_class = "Optional: add a new class",
        picker_hint = "Scroll to choose a class, then tap to Select.",

        select = "Select",
        -- Add or Select Class
        select_your_class = "Add or Select Class",                     -- en

        cancel = "Cancel",
        dont_see_class = "Don’t see your class? Add one below.",
        class_name_label = "Class Name",
        add_one_below = "Add one below.",


        -- Added earlier keys
        words_to_remember = "Words to Remember",
        words_to_remember_help = "Words the learner will catch during the game.",
        success_message = "Success Message",

        -- Success message strings
        saving_success   = "Saving success message...",
        updating_success = "Updating success message...",
        success_saved    = "Success message saved!",
        success_updated  = "Success message updated!",
        success_message_help = "Shown after the learner completes the game.",
        -- NEW STRINGS
        you_completed = "You completed",
        you_completed_level               = "You completed level",
        loading_success_message           = "Loading success message",
        loading_success_message_for_level = "Loading success message for level",

        version = "Version",
        contact_support = "Contact Support",
        kids_privacy = "Privacy Policy",
        visit_website = "Terms of Use",
 
        choose_level = "Choose Level",
        select_level = "Select Level",
        no_levels_found = "No Levels Found",
        find_class = "Find Class",
        class_code = "Class Code",
         dont_have_code = "Don't have a code?",
        use_demo_code  = "Use 12345 to play now!",
        get_code_from_teacher = "Get a code from your teacher.",
        about_smartsheep = "About SmartSheep",
                too_long = "Too long",
        verse_too_long = "Verse too long",
        success_too_long = "Success message too long",

        class_name_required = "Class name required",
        missing_user = "User not found",
        missing_prefix = "Missing prefix",
        saved = "Saved",
        levels = "Levels",

        log_out = "Log Out",
        subscribe = "Subscribe",
        sign_up = "Sign Up",
        create_classes = "Create classes and fun levels for your students",

        paywall_title = "1 Month Free Trial",
        paywall_price_default = "1 month free, then...",
        paywall_price_template = "1 month free, then %s/month",
        paywall_cancel_anytime = "Cancel anytime through Google Play",
        paywall_benefit = "Create and update unlimited classes and levels",

        paywall_start_trial = "Start Free Trial",
        paywall_restore_purchases = "Restore Purchases",

        paywall_loading_price = "Loading price...",
        paywall_loading_google_play_price = "Loading price from Google Play...",

        paywall_status_active = "Premium active.",
        paywall_status_verify_failed = "Could not verify subscription status.",
        paywall_status_login_first = "Please log in first.",
        paywall_status_loading_google_play = "Subscription is still loading from Google Play...",
        paywall_status_product_missing_google_play = "Subscription product not found in Google Play.",
        paywall_status_opening_checkout = "Opening secure Google Play checkout...",
        paywall_status_purchase_cancelled = "Purchase cancelled.",
        paywall_status_purchase_failed = "Purchase failed.",
        paywall_status_purchase_failed_with_error = "Purchase failed: %s",

        paywall_status_verified = "Premium active. Subscription verified.",
        paywall_status_checking = "Checking subscription status...",
        paywall_status_restored = "Premium active. Subscription restored.",
        paywall_status_not_found = "No active subscription found.",
        paywall_status_restore_failed_with_error = "Could not restore subscription: %s",
        paywall_status_product_not_found_short = "Product not found.",
        paywall_status_google_play_details_failed = "Google Play product details could not be loaded.",
        about_body =
    "SmartSheep turns Scripture memory into a fun game.\n\n" ..
    "Catch one word at a time until the verse is completed exactly.\n\n" ..
    "Built for families, classes, and ministries.",
        eraser_coconut = "coconut",    
        eraser_banana  = "banana",
        eraser_leaf    = "leaf",
        eraser_sprig   = "sprig",
        eraser_flower  = "flower",
        eraser_fish    = "fish",
    },

    ----------------------------------------------------------------
    -- Spanish
    ----------------------------------------------------------------
    es = {
        home = "Inicio",
        edit = "Editar",
        greeting = "Hola",
         game_catch = "Atrapa",
        game_catch_desc = "Atrapa las palabras",

        game_match = "Empareja",
        game_match_desc = "Arrastra palabras al lugar",
        word_card_game = "Juego de Tarjetas de Palabras",
        drag_words_instruction = "Arrastra cada tarjeta de palabra al lugar correcto.",
        screen_count = "Pantalla %d de %d",
        no_words_saved = "Primero agrega algunas palabras y luego previsualiza el juego.",
        game_order = "Ordena",
        game_order_desc = "Conecta el orden",
        line_match_game = "Juego de Emparejar Líneas",
        draw_line_instruction = "Dibuja una línea desde cada palabra hasta su lugar correspondiente.",

        player = "Jugador",
        menu = "Menú",
        choose_a_game = "Elegir juego",
        log_in = "Iniciar sesión",
        exit = "Salir",
        language = "Idioma",
        success = "Éxito",
        error = "Error",
        saving = "Guardando...",
        save_failed = "Error al guardar",
        updated = "Actualizado",
        updating = "Actualizando...",
        seed_error = "Error de semilla",
        no_passages_found = "No se encontraron pasajes",
        creating_new_passage = "Creando nuevo pasaje...",
        select_passage  = "Seleccionar pasaje para editar",
        tutorial_welcome_title = "¡Bienvenido!",
        tutorial_welcome_text = "Crea juegos bíblicos divertidos para tus estudiantes. Ellos jugarán lo que tú construyas.",
        tutorial_students_play_title = "Los estudiantes juegan",
        tutorial_students_play_text = "Tus clases y niveles se convierten en juegos para los estudiantes.",
        tutorial_student_app_text = "Tus estudiantes instalan la app SmartSheep para estudiantes. Es gratis y NO tiene anuncios.",
        tutorial_add_class_title = "Agregar clase",
        tutorial_add_class_text = "Toca Agregar clase abajo para crear tu primera clase.",
        tutorial_class_details_title = "Detalles de la clase",
        tutorial_class_details_text = "Los estudiantes accederán a tu juego con el ID generado.",
        tutorial_students_join_title = "Los estudiantes se unen",
        tutorial_students_join_text = "En la app SmartSheep, los estudiantes ingresarán tu ID de clase.",
        tutorial_students_replay_text = "Después de unirse, los estudiantes verán tu clase en su app para jugar una y otra vez.",
        tutorial_tutorials_title = "Tutoriales",
        tutorial_tutorials_text = "Revisa los tutoriales bajo el ? en la parte superior derecha de cada pantalla.",
        tutorial_catch_words = "¡Atrapa las palabras!",
        tutorial_next = "Siguiente ›",

        tutorial_class_settings_title = "Configuración de la clase",
        tutorial_class_settings_text = "Aquí puedes actualizar tu clase.",
        tutorial_change_class_name_title = "Cambiar nombre de la clase",
        tutorial_change_class_name_text = "Toca el campo Nombre de la clase para cambiarlo.",
        tutorial_publish_class_title = "Publicar clase",
        tutorial_publish_class_text = "Toca Publicado cuando tu clase esté lista para los estudiantes.",
        tutorial_save_changes_title = "Guardar cambios",
        tutorial_save_changes_text = "Toca Guardar para actualizar el nombre y la publicación de tu clase.",
        tutorial_add_level_title = "Agregar un nivel",
        tutorial_add_level_text = "Toca Agregar nivel para crear niveles de juego para esta clase.",
        tutorial_class_name_label = "Nombre de la clase:",
        tutorial_sample_class_name = "Escuela Dominical",
        tutorial_draft = "Borrador",
        tutorial_published = "Publicado",
        tutorial_add_level_button = "➕ Agregar nivel",

        tutorial_level_title_title = "Título del nivel",
        tutorial_level_title_text = "Dale un título a tu nivel. Los estudiantes lo verán al elegir qué jugar.",
        tutorial_choose_theme_title = "Elegir tema",
        tutorial_choose_theme_text = "Selecciona un tema para cambiar la apariencia del juego.",
        tutorial_words_to_remember_title = "Palabras para recordar",
        tutorial_words_to_remember_text = "Agrega un versículo o palabras que quieras que los estudiantes recuerden.",
        tutorial_success_message_title = "Mensaje de éxito",
        tutorial_success_message_text = "Agrega ánimo, notas del versículo, planes para la próxima clase o recordatorios.",
        tutorial_preview_game_title = "Vista previa del juego",
        tutorial_preview_game_text = "Toca Vista previa del juego para probarlo antes de que jueguen los estudiantes.",
        tutorial_preview_success_title = "Vista previa del éxito",
        tutorial_preview_success_text = "Toca Vista previa del éxito para ver el mensaje que recibirán los estudiantes.",
        tutorial_sample_level_name = "Principiantes - Salmo 118:1",
        tutorial_sample_theme = "Submarino ▼",
        tutorial_sample_words = "Dios es bueno",
        tutorial_sample_success_message = "¡Buen trabajo! Recuerda este versículo esta semana.",
        preview_game    = "Vista previa del juego",
        preview_success = "Vista previa del éxito",
        edit_level = "Editar nivel",
        save_first = "Guardar primero",
        theme_helper = "Elige un tema para este nivel.",
        add_words_to_remember = "Agregar palabras para recordar",
        add_success_message = "Agregar mensaje de éxito",
        new_code = "Nuevo código",
        published = "Publicado",
        draft = "Borrador",
        loading_classes = "Cargando clases...",
        share_with_students = "Compártelo con tus estudiantes.",
        enter_level_name = "Ingresa un nombre para el nivel",
        save = "Guardar",
        tap_theme_then_done = "Toca un tema y luego pulsa Listo",
        selected_theme = "Seleccionado",
        done = "Listo",
        save_to_preview_edits = "Guarda para previsualizar los cambios",
        missing_user_class = "Falta el usuario o la clase.",
        please_enter_level_name = "Por favor, ingresa un nombre para el nivel.",
        creating_new_level = "Creando nuevo nivel...",
        hint_instruction = "Atrapa las palabras en orden.",
        hint_remove_last_word = "Atrapa %s para borrar la última palabra.",
        hint_tap_panel = "Toca este panel para ver el versículo.",
        missing_level_id = "Falta el ID del nivel.",
        please_select_level_first = "Por favor, selecciona primero un nivel.",
        deleting = "Eliminando",
        delete_failed = "No se pudo eliminar.",
        needs_text = "Falta texto",
        delete_level = "¿Eliminar nivel?",
        delete_level_msg = "Esto eliminará este nivel.",
        delete = "Eliminar",
        dont_see_level = "¿No ves el nivel que quieres? Agrega uno abajo.",
        add_level = "Agregar nivel",
        manage = "Administrar",
        no_success_messages_found = "No se encontraron mensajes de éxito",
        loaded = "Cargado",
        title_topic_or_passage = "Título, tema o pasaje",
        add_new = "Agregar nuevo",
        select_class = "Selecciona tu clase",
        select_label = "Seleccionar clase",
        no_class_selected = "No se ha seleccionado ninguna clase",
        no_classes_available = "No hay clases disponibles",
        add_class = "Agregar clase",
        save_class = "Guardar clase",
        load_class = "Cargando clase",
        load_failed = "Error al cargar",
        load_error = "Fallo de carga",
        loading = "Cargando...",
        please_select_class = "Por favor, selecciona una clase antes de continuar.",
        ok = "Aceptar",
        class_id = "ID de clase",
        class_name = "Nombre de la clase",
        error_missing = "Por favor, ingresa el ID y el nombre de la clase.",
        success_added = "¡Clase agregada!",
        error_connection = "No se pudo conectar al servidor. Inténtalo de nuevo más tarde.",
        next = "Siguiente",
        back = "Atrás",
        select_language = "Seleccionar idioma",
        language_updated = "Idioma actualizado",
        restart_notice = "El cambio se aplicará de inmediato.",
        play_game = "Jugar",
        create = "Crear",
        enter_code = "Ingresar código",
        hint = "Pista",
        please_enter_class_code = "Por favor, ingresa un código de clase.",
        please_login = "Por favor, inicia sesión.",
        please_login_or_enter_class_code = "Inicia sesión o ingresa un código de clase.",
        welcome = "Bienvenido",
        welcome_to = "Bienvenido a",
        theme = "Tema",
        about    = "Acerca de",
        support  = "Soporte",
        settings = "Configuración",
        optional_add_class = "Opcional: agregar una nueva clase",
        picker_hint = "Desplázate para elegir una clase y luego toca para Seleccionar.",

        select = "Seleccionar",
        -- Add or Select Class
        select_your_class = "Agregar o seleccionar clase",             -- es

        cancel = "Cancelar",
        dont_see_class = "¿No ves tu clase? Agrega una abajo.",
        class_name_label = "Nombre de la clase",
        add_one_below = "Agrega una abajo.",


        words_to_remember = "Palabras para Recordar",
         words_to_remember_help = "Palabras que el estudiante atrapará durante el juego.",
        success_message = "Mensaje de Éxito",

        saving_success   = "Guardando mensaje de éxito...",
        updating_success = "Actualizando mensaje de éxito...",
        success_saved    = "¡Mensaje de éxito guardado!",
        success_updated  = "¡Mensaje de éxito actualizado!",
        success_message_help = "Se muestra cuando el alumno completa el juego.",

        you_completed = "Has completado",
        you_completed_level               = "Has completado el nivel",
        loading_success_message           = "Cargando mensaje de éxito",
        loading_success_message_for_level = "Cargando mensaje de éxito para el nivel",
      
        version = "Versión",
        contact_support = "Contactar Soporte",
        kids_privacy = "Política de Privacidad",
        visit_website = "Términos de Uso",

        choose_level = "Elegir nivel",
        select_level = "Seleccionar nivel",
        no_levels_found = "No se encontraron niveles",
        find_class = "Buscar clase",
        class_code = "Código de clase",
        dont_have_code = "¿No tienes un código?",
        use_demo_code  = "¡Usa 12345 para jugar ahora!",
        get_code_from_teacher = "Consigue un código de tu profesor.",
        about_smartsheep = "Acerca de SmartSheep",
                too_long = "Demasiado largo",
        verse_too_long = "Verso demasiado largo",
        success_too_long = "Mensaje de éxito demasiado largo",

        class_name_required = "Se requiere el nombre de la clase",
        missing_user = "Usuario no encontrado",
        missing_prefix = "Falta el prefijo",
        saved = "Guardado",
        levels = "Niveles",

        log_out = "Cerrar sesión",
        subscribe = "Suscribirse",
        sign_up = "Registrarse",
        create_classes = "Crea clases y niveles divertidos para tus estudiantes",

        paywall_title = "Prueba gratuita de 1 mes",
        paywall_price_default = "1 mes gratis, luego...",
        paywall_price_template = "1 mes gratis, luego %s/mes",
        paywall_cancel_anytime = "Cancela en cualquier momento desde Google Play",
        paywall_benefit = "Crea y actualiza clases y niveles ilimitados",

        paywall_start_trial = "Iniciar prueba gratuita",
        paywall_restore_purchases = "Restaurar compras",

        paywall_loading_price = "Cargando precio...",
        paywall_loading_google_play_price = "Cargando precio desde Google Play...",

        paywall_status_active = "Premium activo.",
        paywall_status_verify_failed = "No se pudo verificar la suscripción.",
        paywall_status_login_first = "Por favor inicia sesión primero.",
        paywall_status_loading_google_play = "La suscripción todavía se está cargando desde Google Play...",
        paywall_status_product_missing_google_play = "Producto de suscripción no encontrado en Google Play.",
        paywall_status_opening_checkout = "Abriendo pago seguro en Google Play...",
        paywall_status_purchase_cancelled = "Compra cancelada.",
        paywall_status_purchase_failed = "Compra fallida.",
        paywall_status_purchase_failed_with_error = "Compra fallida: %s",

        paywall_status_verified = "Premium activo. Suscripción verificada.",
        paywall_status_checking = "Verificando suscripción...",
        paywall_status_restored = "Premium activo. Suscripción restaurada.",
        paywall_status_not_found = "No se encontró una suscripción activa.",
        paywall_status_restore_failed_with_error = "No se pudo restaurar la suscripción: %s",
        paywall_status_product_not_found_short = "Producto no encontrado.",
        paywall_status_google_play_details_failed = "No se pudieron cargar los detalles del producto de Google Play.",
        about_body =
    "SmartSheep convierte la memorización de las Escrituras en un juego divertido.\n\n" ..
    "Atrapa una palabra a la vez hasta completar el versículo exactamente.\n\n" ..
    "Creado para familias, clases y ministerios.",
        eraser_coconut = "coco",
        eraser_banana  = "plátano",
        eraser_leaf    = "hoja",
        eraser_sprig   = "ramita",
        eraser_flower  = "flor",
        eraser_fish    = "pez",

},

    ----------------------------------------------------------------
    -- French
    ----------------------------------------------------------------
    fr = {
        home = "Accueil",
        edit = "Modifier",
        greeting = "Bonjour",
        game_catch = "Attrape",
        game_catch_desc = "Attrape les mots",

        game_match = "Associe",
        game_match_desc = "Fais glisser les mots",
        word_card_game = "Jeu de Cartes de Mots",
        drag_words_instruction = "Faites glisser chaque carte de mot au bon endroit.",
        screen_count = "Écran %d sur %d",
        no_words_saved = "Ajoutez d’abord quelques mots, puis prévisualisez le jeu.",
        game_order = "Ordre",
        game_order_desc = "Relie le bon ordre",
        line_match_game = "Jeu de Correspondance par Lignes",
        draw_line_instruction = "Trace une ligne de chaque mot vers son emplacement correspondant.",
        player = "Joueur",
        menu = "Menu",
        choose_a_game = "Choisir un jeu",
        log_in = "Connexion",
        exit = "Quitter",
        language = "Langue",
        success = "Succès",
        error = "Erreur",
        saving = "Enregistrement...",
        save_failed = "Échec de l’enregistrement",
        updated = "Mis à jour",
        updating = "Mise à jour...",
        seed_error = "Erreur de génération",
        no_passages_found = "Aucun passage trouvé",
        creating_new_passage = "Création d’un nouveau passage...",
        select_passage  = "Sélectionner le passage à modifier",
        tutorial_welcome_title = "Bienvenue !",
        tutorial_welcome_text = "Créez des jeux bibliques amusants pour vos élèves. Ils joueront à ce que vous créez.",
        tutorial_students_play_title = "Les élèves jouent",
        tutorial_students_play_text = "Vos classes et niveaux deviennent des jeux pour les élèves.",
        tutorial_student_app_text = "Vos élèves installent l’application SmartSheep pour élèves. Elle est gratuite et SANS publicité.",
        tutorial_add_class_title = "Ajouter une classe",
        tutorial_add_class_text = "Appuyez sur Ajouter une classe ci-dessous pour créer votre première classe.",
        tutorial_class_details_title = "Détails de la classe",
        tutorial_class_details_text = "Les élèves accéderont à votre jeu avec l’identifiant généré.",
        tutorial_students_join_title = "Les élèves rejoignent",
        tutorial_students_join_text = "Dans l’application SmartSheep, les élèves saisiront votre identifiant de classe.",
        tutorial_students_replay_text = "Après avoir rejoint la classe, les élèves la verront dans leur application et pourront jouer encore et encore.",
        tutorial_tutorials_title = "Tutoriels",
        tutorial_tutorials_text = "Consultez les tutoriels sous le ? en haut à droite de chaque écran.",
        tutorial_catch_words = "Attrape les mots !",
        tutorial_next = "Suivant ›",

        tutorial_class_settings_title = "Paramètres de la classe",
        tutorial_class_settings_text = "C’est ici que vous pouvez mettre à jour votre classe.",
        tutorial_change_class_name_title = "Modifier le nom de la classe",
        tutorial_change_class_name_text = "Appuyez sur le champ Nom de la classe pour la renommer.",
        tutorial_publish_class_title = "Publier la classe",
        tutorial_publish_class_text = "Appuyez sur Publiée lorsque votre classe est prête pour les élèves.",
        tutorial_save_changes_title = "Enregistrer les modifications",
        tutorial_save_changes_text = "Appuyez sur Enregistrer pour mettre à jour le nom et l’état de publication de votre classe.",
        tutorial_add_level_title = "Ajouter un niveau",
        tutorial_add_level_text = "Appuyez sur Ajouter un niveau pour créer des niveaux de jeu pour cette classe.",
        tutorial_class_name_label = "Nom de la classe :",
        tutorial_sample_class_name = "École du dimanche",
        tutorial_draft = "Brouillon",
        tutorial_published = "Publiée",
        tutorial_add_level_button = "➕ Ajouter un niveau",

        tutorial_level_title_title = "Titre du niveau",
        tutorial_level_title_text = "Donnez un titre à votre niveau. Les élèves le verront lorsqu’ils choisiront à quoi jouer.",
        tutorial_choose_theme_title = "Choisir un thème",
        tutorial_choose_theme_text = "Choisissez un thème pour modifier l’apparence du jeu.",
        tutorial_words_to_remember_title = "Mots à retenir",
        tutorial_words_to_remember_text = "Ajoutez un verset à mémoriser ou des mots que vous souhaitez que les élèves retiennent.",
        tutorial_success_message_title = "Message de réussite",
        tutorial_success_message_text = "Ajoutez des encouragements, des notes sur le verset, des plans pour la prochaine classe ou des rappels.",
        tutorial_preview_game_title = "Aperçu du jeu",
        tutorial_preview_game_text = "Appuyez sur Aperçu du jeu pour tester le jeu avant que les élèves ne jouent.",
        tutorial_preview_success_title = "Aperçu du message de réussite",
        tutorial_preview_success_text = "Appuyez sur Aperçu du message de réussite pour voir le message que recevront les élèves après avoir terminé.",
        tutorial_sample_level_name = "Débutants - Psaume 118:1",
        tutorial_sample_theme = "Sous-marin ▼",
        tutorial_sample_words = "Dieu est bon",
        tutorial_sample_success_message = "Excellent travail ! Souviens-toi de ce verset cette semaine.",
        preview_game    = "Aperçu du jeu",
        preview_success = "Aperçu de la réussite",
        edit_level = "Modifier le niveau",
        save_first = "Enregistrer d'abord",
        theme_helper = "Choisissez un thème pour ce niveau.",
        add_words_to_remember = "Ajouter des mots à retenir",
        add_success_message = "Ajouter un message de réussite",
        new_code = "Nouveau code",
        published = "Publié",
        draft = "Brouillon",
        loading_classes = "Chargement des classes...",
        share_with_students = "Partagez ceci avec vos élèves.",
        enter_level_name = "Entrez un nom de niveau",
        save = "Enregistrer",
        tap_theme_then_done = "Touchez un thème, puis Terminé",
        selected_theme = "Sélectionné",
        done = "Terminé",
        save_to_preview_edits = "Enregistrez pour prévisualiser les modifications",
        missing_user_class = "Utilisateur ou classe manquant.",
        please_enter_level_name = "Veuillez entrer un nom de niveau.",
        creating_new_level = "Création d’un nouveau niveau...",
        hint_instruction = "Attrape les mots dans l'ordre.",
        hint_remove_last_word = "Attrape %s pour effacer le dernier mot", 
        hint_tap_panel = "Touchez ce panneau pour voir le verset.",
        missing_level_id = "ID de niveau manquant.",
        please_select_level_first = "Veuillez d’abord sélectionner un niveau.",
        deleting = "Suppression",
        delete_failed = "Échec de la suppression.",
        needs_text = "Texte requis",
        delete_level = "Supprimer le niveau ?",
        delete_level_msg = "Cela supprimera ce niveau.",
        delete = "Supprimer",
        dont_see_level = "Vous ne voyez pas le niveau souhaité ? Ajoutez-en un ci-dessous.",
        add_level = "Ajouter un niveau",
        manage = "Gérer",
        no_success_messages_found = "Aucun message de réussite trouvé",
        loaded = "Chargé",
        title_topic_or_passage = "Titre, sujet ou passage",
        add_new = "Ajouter nouveau",
        select_class = "Sélectionnez votre classe",
        select_label = "Choisir une classe",
        no_class_selected = "Aucune classe sélectionnée",
        no_classes_available = "Aucune classe disponible",
        add_class = "Ajouter une classe",
        save_class = "Enregistrer la classe",
        load_class = "Chargement de la classe",
        load_failed = "Échec du chargement",
        load_error = "Erreur de chargement",
        loading = "Chargement...",
        please_select_class = "Veuillez sélectionner une classe avant de continuer.",
        ok = "OK",
        class_id = "ID de la classe",
        class_name = "Nom de la classe",
        error_missing = "Veuillez entrer l’ID et le nom de la classe.",
        success_added = "Classe ajoutée !",
        error_connection = "Impossible de se connecter au serveur. Veuillez réessayer plus tard.",
        next = "Suivant",
        back = "Retour",
        select_language = "Choisir la langue",
        language_updated = "Langue mise à jour",
        restart_notice = "Le changement s’appliquera immédiatement.",
        play_game = "Jouer",
        create = "Créer",
        enter_code = "Entrer le code",
        hint = "Indice",
        please_enter_class_code = "Veuillez entrer un code de classe.",
        please_login = "Veuillez vous connecter.",
        please_login_or_enter_class_code = "Connectez-vous ou entrez un code de classe.",
        welcome = "Bienvenue",
        welcome_to = "Bienvenue à",
        theme = "Thème",
        about    = "À propos",
        support  = "Assistance",
        settings = "Paramètres",

        optional_add_class = "Facultatif : ajouter une nouvelle classe",
        picker_hint = "Faites défiler pour choisir une classe, puis appuyez pour sélectionner.",

        select = "Sélectionner",
        -- Add or Select Class
        select_your_class = "Ajouter ou sélectionner une classe",      -- fr

        cancel = "Annuler",
        dont_see_class = "Vous ne voyez pas votre classe ? Ajoutez-en une ci-dessous.",
        class_name_label = "Nom de la classe",
        add_one_below = "Ajoutez-en une ci-dessous.",

        words_to_remember = "Mots à Retenir",
        words_to_remember_help = "Mots que l’élève attrapera pendant le jeu.",
        success_message = "Message de Réussite",

        saving_success   = "Enregistrement du message de réussite...",
        updating_success = "Mise à jour du message de réussite...",
        success_saved    = "Message de réussite enregistré !",
        success_updated  = "Message de réussite mis à jour !",
        success_message_help = "Affiché lorsque l’élève termine le jeu.",

        you_completed = "Vous avez terminé",
        you_completed_level               = "Vous avez terminé le niveau",
        loading_success_message           = "Chargement du message de réussite",
        loading_success_message_for_level = "Chargement du message de réussite pour le niveau",

        version = "Version",
        contact_support = "Contacter le Support",
        kids_privacy = "Politique de Confidentialité",
        visit_website = "Conditions d’Utilisation",

        choose_level = "Choisir un niveau",
        select_level = "Sélectionner un niveau",
        no_levels_found = "Aucun niveau trouvé",
        find_class = "Trouver la classe",
        class_code = "Code de classe",
        dont_have_code = "Vous n’avez pas de code ?",
        use_demo_code  = "Utilisez 12345 pour jouer maintenant !",
        get_code_from_teacher = "Obtiens un code de ton enseignant.",
        about_smartsheep = "À propos de SmartSheep",
                too_long = "Trop long",
        verse_too_long = "Verset trop long",
        success_too_long = "Message de réussite trop long",

        class_name_required = "Nom de classe requis",
        missing_user = "Utilisateur introuvable",
        missing_prefix = "Préfixe manquant",
        saved = "Enregistré",
        levels = "Niveaux",

        log_out = "Se déconnecter",
        subscribe = "S'abonner",
        sign_up = "S'inscrire",
        create_classes = "Créez des classes et des niveaux amusants pour vos élèves",

        paywall_title = "Essai gratuit de 1 mois",
        paywall_price_default = "1 mois gratuit, puis...",
        paywall_price_template = "1 mois gratuit, puis %s/mois",
        paywall_cancel_anytime = "Annulez à tout moment via Google Play",
        paywall_benefit = "Créez et mettez à jour des classes et niveaux illimités",

        paywall_start_trial = "Démarrer l'essai gratuit",
        paywall_restore_purchases = "Restaurer les achats",

        paywall_loading_price = "Chargement du prix...",
        paywall_loading_google_play_price = "Chargement du prix depuis Google Play...",

        paywall_status_active = "Premium actif.",
        paywall_status_verify_failed = "Impossible de vérifier l'abonnement.",
        paywall_status_login_first = "Veuillez d'abord vous connecter.",
        paywall_status_loading_google_play = "L'abonnement est encore en cours de chargement depuis Google Play...",
        paywall_status_product_missing_google_play = "Produit d'abonnement introuvable dans Google Play.",
        paywall_status_opening_checkout = "Ouverture du paiement sécurisé Google Play...",
        paywall_status_purchase_cancelled = "Achat annulé.",
        paywall_status_purchase_failed = "Échec de l'achat.",
        paywall_status_purchase_failed_with_error = "Échec de l'achat : %s",

        paywall_status_verified = "Premium actif. Abonnement vérifié.",
        paywall_status_checking = "Vérification de l'abonnement...",
        paywall_status_restored = "Premium actif. Abonnement restauré.",
        paywall_status_not_found = "Aucun abonnement actif trouvé.",
        paywall_status_restore_failed_with_error = "Impossible de restaurer l'abonnement : %s",
        paywall_status_product_not_found_short = "Produit introuvable.",
        paywall_status_google_play_details_failed = "Les détails du produit Google Play n'ont pas pu être chargés.",
        about_body =
    "SmartSheep transforme la mémorisation des Écritures en un jeu amusant.\n\n" ..
    "Attrapez un mot à la fois jusqu’à ce que le verset soit complété exactement.\n\n" ..
    "Conçu pour les familles, les classes et les ministères.",
        eraser_coconut = "noix de coco",
        eraser_banana  = "banane",
        eraser_leaf    = "feuille",
        eraser_sprig   = "brindille",
        eraser_flower  = "fleur",   
        eraser_fish    = "poisson",
    },

    ----------------------------------------------------------------
    -- German
    ----------------------------------------------------------------
    de = {
        home = "Start",
        edit = "Bearbeiten",
        greeting = "Hallo",
        game_catch = "Fangen",
        game_catch_desc = "Fange die Wörter",

        game_match = "Zuordnen",
        game_match_desc = "Ziehe Wörter an die Stelle",
        word_card_game = "Wortkarten-Spiel",
        drag_words_instruction = "Ziehe jede Wortkarte an die richtige Stelle.",
        screen_count = "Bildschirm %d von %d",
        no_words_saved = "Füge zuerst einige Wörter hinzu und sieh dir dann die Vorschau des Spiels an.",
        game_order = "Reihenfolge",
        game_order_desc = "Verbinde die Reihenfolge",
        line_match_game = "Linien-Zuordnungsspiel",
        draw_line_instruction = "Ziehe eine Linie von jedem Wort zu seiner passenden Stelle.",
        player = "Spieler",
        menu = "Menü",
        choose_a_game = "Spiel auswählen",
        log_in = "Anmelden",
        exit = "Beenden",
        language = "Sprache",
        success = "Erfolg",
        error = "Fehler",
        saving = "Speichern...",
        save_failed = "Speichern fehlgeschlagen",
        updated = "Aktualisiert",
        updating = "Aktualisierung...",
        seed_error = "Seed-Fehler",
        no_passages_found = "Keine Passagen gefunden",
        creating_new_passage = "Neuer Abschnitt wird erstellt...",
        select_passage  = "Passage zum Bearbeiten auswählen",
        tutorial_welcome_title = "Willkommen!",
        tutorial_welcome_text = "Erstellen Sie lustige Bibelspiele für Ihre Schüler. Sie spielen, was Sie erstellen.",
        tutorial_students_play_title = "Schüler spielen",
        tutorial_students_play_text = "Ihre Klassen und Levels werden zu Spielen für Schüler.",
        tutorial_student_app_text = "Ihre Schüler installieren die SmartSheep-Schüler-App. Sie ist kostenlos und enthält KEINE Werbung.",
        tutorial_add_class_title = "Klasse hinzufügen",
        tutorial_add_class_text = "Tippen Sie unten auf Klasse hinzufügen, um Ihre erste Klasse zu erstellen.",
        tutorial_class_details_title = "Klassendetails",
        tutorial_class_details_text = "Schüler greifen mit der generierten ID auf Ihr Spiel zu.",
        tutorial_students_join_title = "Schüler treten bei",
        tutorial_students_join_text = "In der SmartSheep-App geben die Schüler Ihre Klassen-ID ein.",
        tutorial_students_replay_text = "Nach dem Beitritt sehen die Schüler Ihre Klasse in ihrer App und können immer wieder spielen.",
        tutorial_tutorials_title = "Tutorials",
        tutorial_tutorials_text = "Sehen Sie sich die Tutorials unter dem ? oben rechts auf jedem Bildschirm an.",
        tutorial_catch_words = "Fange die Wörter!",
        tutorial_next = "Weiter ›",

        tutorial_class_settings_title = "Klasseneinstellungen",
        tutorial_class_settings_text = "Hier können Sie Ihre Klasse aktualisieren.",
        tutorial_change_class_name_title = "Klassennamen ändern",
        tutorial_change_class_name_text = "Tippen Sie auf das Feld Klassenname, um Ihre Klasse umzubenennen.",
        tutorial_publish_class_title = "Klasse veröffentlichen",
        tutorial_publish_class_text = "Tippen Sie auf Veröffentlicht, wenn Ihre Klasse für die Schüler bereit ist.",
        tutorial_save_changes_title = "Änderungen speichern",
        tutorial_save_changes_text = "Tippen Sie auf Speichern, um den Klassennamen und die Veröffentlichungseinstellung zu aktualisieren.",
        tutorial_add_level_title = "Level hinzufügen",
        tutorial_add_level_text = "Tippen Sie auf Level hinzufügen, um Spiellevel für diese Klasse zu erstellen.",
        tutorial_class_name_label = "Klassenname:",
        tutorial_sample_class_name = "Sonntagsschule",
        tutorial_draft = "Entwurf",
        tutorial_published = "Veröffentlicht",
        tutorial_add_level_button = "➕ Level hinzufügen",

        tutorial_level_title_title = "Leveltitel",
        tutorial_level_title_text = "Geben Sie Ihrem Level einen Titel. Die Schüler sehen ihn, wenn sie auswählen, was sie spielen möchten.",
        tutorial_choose_theme_title = "Thema auswählen",
        tutorial_choose_theme_text = "Wählen Sie ein Thema, um das Aussehen des Spiels zu ändern.",
        tutorial_words_to_remember_title = "Wörter zum Merken",
        tutorial_words_to_remember_text = "Fügen Sie einen Merkvers oder Wörter hinzu, die sich die Schüler merken sollen.",
        tutorial_success_message_title = "Erfolgsmeldung",
        tutorial_success_message_text = "Fügen Sie Ermutigungen, Versnotizen, Pläne für die nächste Stunde oder Erinnerungen hinzu.",
        tutorial_preview_game_title = "Spielvorschau",
        tutorial_preview_game_text = "Tippen Sie auf Spielvorschau, um das Spiel zu testen, bevor die Schüler spielen.",
        tutorial_preview_success_title = "Erfolgsvorschau",
        tutorial_preview_success_text = "Tippen Sie auf Erfolgsvorschau, um die Nachricht zu sehen, die Schüler nach dem Abschluss erhalten.",
        tutorial_sample_level_name = "Anfänger - Psalm 118:1",
        tutorial_sample_theme = "Unterwasser ▼",
        tutorial_sample_words = "Gott ist gut",
        tutorial_sample_success_message = "Großartige Arbeit! Denke diese Woche an diesen Vers.",
        preview_game    = "Spielvorschau",
        preview_success = "Erfolgsvorschau",
        edit_level = "Level bearbeiten",
        save_first = "Zuerst speichern",
        theme_helper = "Wählen Sie ein Thema für dieses Level.",
        add_words_to_remember = "Wörter zum Merken hinzufügen",
        add_success_message = "Erfolgsmeldung hinzufügen",
        new_code = "Neuer Code",
        published = "Veröffentlicht",
        draft = "Entwurf",
        loading_classes = "Klassen werden geladen...",
        share_with_students = "Teile dies mit deinen Schülern.",
        enter_level_name = "Gib einen Levelnamen ein",
        save = "Speichern",
        tap_theme_then_done = "Tippe auf ein Thema und dann auf Fertig",
        selected_theme = "Ausgewählt",
        done = "Fertig",
        save_to_preview_edits = "Speichere, um die Änderungen in der Vorschau zu sehen",
        missing_user_class = "Benutzer oder Klasse fehlt.",
        please_enter_level_name = "Bitte gib einen Levelnamen ein.",
        creating_new_level = "Neues Level wird erstellt...",
        hint_instruction = "Fange die Wörter in der richtigen Reihenfolge.",
        hint_remove_last_word = "Fange %s, um das letzte Wort zu löschen.",
        hint_tap_panel = "Tippe auf dieses Feld, um den Vers zu sehen.",
        missing_level_id = "Level-ID fehlt.",
        please_select_level_first = "Bitte wähle zuerst ein Level aus.",
        deleting = "Wird gelöscht",
        delete_failed = "Löschen fehlgeschlagen.",
        needs_text = "Text fehlt",
        delete_level = "Level löschen?",
        delete_level_msg = "Dieses Level wird gelöscht.",
        delete = "Löschen",
        dont_see_level = "Siehst du das gewünschte Level nicht? Füge unten eins hinzu.",
        add_level = "Level hinzufügen",
        manage = "Verwalten",
        no_success_messages_found = "Keine Erfolgsmeldungen gefunden",
        loaded = "Geladen",
        title_topic_or_passage = "Titel, Thema oder Passage",
        add_new = "Neu hinzufügen",
        select_class = "Wähle deine Klasse",
        select_label = "Klasse auswählen",
        no_class_selected = "Keine Klasse ausgewählt",
        no_classes_available = "Keine Klassen verfügbar",
        add_class = "Klasse hinzufügen",
        save_class = "Klasse speichern",
        load_class = "Klasse wird geladen",
        load_failed = "Laden fehlgeschlagen",
        load_error = "Ladefehler",
        loading = "Wird geladen...",
        please_select_class = "Bitte wähle eine Klasse, bevor du fortfährst.",
        ok = "OK",
        class_id = "Klassen-ID",
        class_name = "Klassenname eingeben",
        error_missing = "Bitte gib sowohl die Klassen-ID als auch den Namen ein.",
        success_added = "Klasse hinzugefügt!",
        error_connection = "Verbindung zum Server fehlgeschlagen. Bitte später erneut versuchen.",
        next = "Weiter",
        back = "Zurück",
        select_language = "Sprache auswählen",
        language_updated = "Sprache aktualisiert",
        restart_notice = "Die Änderung wird sofort angewendet.",
        play_game = "Spiel starten",
        create = "Erstellen",
        enter_code = "Code eingeben",
        hint = "Hinweis",
        please_enter_class_code = "Bitte gib einen Klassencode ein.",
        please_login = "Bitte melde dich an.",
        please_login_or_enter_class_code = "Bitte melde dich an oder gib einen Klassencode ein.",
        welcome = "Willkommen",
        welcome_to = "Willkommen bei",
        theme = "Thema",
        about    = "Über",
        support  = "Unterstützung",
        settings = "Einstellungen",
        optional_add_class = "Optional: neue Klasse hinzufügen",
        picker_hint = "Scrollen Sie, um eine Klasse auszuwählen, und tippen Sie zum Auswählen.",

        select = "Auswählen",
        -- Add or Select Class
        select_your_class = "Klasse hinzufügen oder auswählen",        -- de

        cancel = "Abbrechen",
        dont_see_class = "Sehen Sie Ihre Klasse nicht? Fügen Sie unten eine hinzu.",
        class_name_label = "Klassenname",
        add_one_below = "Fügen Sie unten eine hinzu.",

        words_to_remember = "Worte zum Merken",
        words_to_remember_help = "Wörter, die der Lernende im Spiel fängt.",
        success_message = "Erfolgsmeldung",
        picker_hint = "Scrollen Sie, um eine Klasse auszuwählen, und tippen Sie zum Auswählen.",

        saving_success   = "Erfolgsmeldung wird gespeichert...",
        updating_success = "Erfolgsmeldung wird aktualisiert...",
        success_saved    = "Erfolgsmeldung gespeichert!",
        success_updated  = "Erfolgsmeldung aktualisiert!",
        success_message_help = "Wird angezeigt, wenn der Lernende das Spiel beendet.",

        you_completed = "Du hast abgeschlossen",
        you_completed_level               = "Du hast das Level abgeschlossen",
        loading_success_message           = "Erfolgsmeldung wird geladen",
        loading_success_message_for_level = "Erfolgsmeldung für das Level wird geladen",
    
        version = "Version",
        contact_support = "Unterstützungsgruppe",
        kids_privacy = "Datenschutzrichtlinie",
        visit_website = "Nutzungsbedingungen",

        choose_level = "Level auswählen",
        select_level = "Level auswählen",
        no_levels_found = "Keine Level gefunden",
        find_class = "Klasse finden",
        class_code = "Klassencode",
        dont_have_code = "Keinen Code?",
        use_demo_code  = "Nutze 12345, um jetzt zu spielen!",
        get_code_from_teacher = "Hol dir einen Code von deiner Lehrkraft.",
        about_smartsheep = "Über SmartSheep",
                too_long = "Zu lang",
        verse_too_long = "Vers zu lang",
        success_too_long = "Erfolgsmeldung zu lang",

        class_name_required = "Klassenname erforderlich",
        missing_user = "Benutzer nicht gefunden",
        missing_prefix = "Präfix fehlt",
        saved = "Gespeichert",
        levels = "Level",

        log_out = "Abmelden",
        subscribe = "Abonnieren",
        sign_up = "Registrieren",
        create_classes = "Erstellen Sie Klassen und unterhaltsame Levels für Ihre Schüler",

        paywall_title = "1 Monat kostenlos testen",
        paywall_price_default = "1 Monat kostenlos, dann...",
        paywall_price_template = "1 Monat kostenlos, dann %s/Monat",
        paywall_cancel_anytime = "Jederzeit über Google Play kündbar",
        paywall_benefit = "Unbegrenzt Klassen und Levels erstellen und aktualisieren",

        paywall_start_trial = "Kostenlose Testphase starten",
        paywall_restore_purchases = "Käufe wiederherstellen",

        paywall_loading_price = "Preis wird geladen...",
        paywall_loading_google_play_price = "Preis wird von Google Play geladen...",

        paywall_status_active = "Premium aktiv.",
        paywall_status_verify_failed = "Abonnementstatus konnte nicht überprüft werden.",
        paywall_status_login_first = "Bitte zuerst anmelden.",
        paywall_status_loading_google_play = "Das Abonnement wird noch von Google Play geladen...",
        paywall_status_product_missing_google_play = "Abonnementprodukt in Google Play nicht gefunden.",
        paywall_status_opening_checkout = "Sicherer Google Play-Bezahlvorgang wird geöffnet...",
        paywall_status_purchase_cancelled = "Kauf abgebrochen.",
        paywall_status_purchase_failed = "Kauf fehlgeschlagen.",
        paywall_status_purchase_failed_with_error = "Kauf fehlgeschlagen: %s",

        paywall_status_verified = "Premium aktiv. Abonnement verifiziert.",
        paywall_status_checking = "Abonnementstatus wird überprüft...",
        paywall_status_restored = "Premium aktiv. Abonnement wiederhergestellt.",
        paywall_status_not_found = "Kein aktives Abonnement gefunden.",
        paywall_status_restore_failed_with_error = "Abonnement konnte nicht wiederhergestellt werden: %s",
        paywall_status_product_not_found_short = "Produkt nicht gefunden.",
        paywall_status_google_play_details_failed = "Google Play-Produktdetails konnten nicht geladen werden.",
        about_body =
    "SmartSheep macht das Bibelvers-Auswendiglernen zu einem unterhaltsamen Spiel.\n\n" ..
    "Fange ein Wort nach dem anderen, bis der Vers exakt vervollständigt ist.\n\n" ..
    "Entwickelt für Familien, Klassen und Gemeinden.",
        eraser_coconut = "Kokosnuss",
        eraser_banana  = "Banane",
        eraser_leaf    = "Blatt",
        eraser_sprig   = "Zweig",
        eraser_flower  = "Blume",
        eraser_fish    = "Fisch",


    },

    ----------------------------------------------------------------
    -- Simplified Chinese
    ----------------------------------------------------------------
    zh = {
        home = "主页",
        edit = "编辑",
        greeting = "你好",
        game_catch = "捕捉",
        game_catch_desc = "捕捉单词",

        game_match = "配对",
        game_match_desc = "拖动单词到正确位置",
        word_card_game = "单词卡片游戏",
        drag_words_instruction = "将每张单词卡拖到正确的位置。",
        screen_count = "第 %d 屏，共 %d 屏",
        no_words_saved = "请先添加一些单词，然后预览游戏。",
        game_order = "排序",
        game_order_desc = "连接正确顺序",
        line_match_game = "连线配对游戏",
        draw_line_instruction = "从每个单词画一条线到对应的位置。",
        player = "玩家",
        menu = "菜单",
        choose_a_game = "选择游戏",
        log_in = "登录",
        exit = "退出",
        language = "语言",
        success = "成功",
        error = "错误",
        saving = "正在保存...",
        save_failed = "保存失败",
        updated = "已更新",
        updating = "正在更新...",
        seed_error = "生成错误",
        no_passages_found = "未找到任何段落",
        creating_new_passage = "正在创建新段落...",
        select_passage  = "选择要编辑的段落",
        tutorial_welcome_title = "欢迎！",
        tutorial_welcome_text = "为你的学生创建有趣的圣经游戏。他们会玩你创建的内容。",
        tutorial_students_play_title = "学生开始游戏",
        tutorial_students_play_text = "你的班级和关卡会变成学生可以玩的游戏。",
        tutorial_student_app_text = "你的学生安装 SmartSheep 学生版应用。它是免费的，并且没有广告。",
        tutorial_add_class_title = "添加班级",
        tutorial_add_class_text = "点击下面的“添加班级”来创建你的第一个班级。",
        tutorial_class_details_title = "班级详情",
        tutorial_class_details_text = "学生将使用生成的 ID 进入你的游戏。",
        tutorial_students_join_title = "学生加入",
        tutorial_students_join_text = "在 SmartSheep 应用中，学生将输入你的班级 ID。",
        tutorial_students_replay_text = "加入后，学生会在应用中看到你的班级，并可以反复游戏。",
        tutorial_tutorials_title = "教程",
        tutorial_tutorials_text = "在每个屏幕右上角的 ? 下查看教程。",
        tutorial_catch_words = "接住单词！",
        tutorial_next = "下一步 ›",

        tutorial_class_settings_title = "班级设置",
        tutorial_class_settings_text = "你可以在这里更新班级信息。",
        tutorial_change_class_name_title = "修改班级名称",
        tutorial_change_class_name_text = "点击班级名称框来重命名你的班级。",
        tutorial_publish_class_title = "发布班级",
        tutorial_publish_class_text = "当班级准备好供学生使用时，点击“已发布”。",
        tutorial_save_changes_title = "保存更改",
        tutorial_save_changes_text = "点击保存以更新班级名称和发布设置。",
        tutorial_add_level_title = "添加关卡",
        tutorial_add_level_text = "点击添加关卡，为该班级创建游戏关卡。",
        tutorial_class_name_label = "班级名称：",
        tutorial_sample_class_name = "主日学",
        tutorial_draft = "草稿",
        tutorial_published = "已发布",
        tutorial_add_level_button = "➕ 添加关卡",

        tutorial_level_title_title = "关卡标题",
        tutorial_level_title_text = "为你的关卡设置一个标题。学生在选择游戏时会看到它。",
        tutorial_choose_theme_title = "选择主题",
        tutorial_choose_theme_text = "选择一个主题来改变游戏外观。",
        tutorial_words_to_remember_title = "需要记住的内容",
        tutorial_words_to_remember_text = "添加你希望学生记住的经文或词语。",
        tutorial_success_message_title = "成功消息",
        tutorial_success_message_text = "添加鼓励的话、经文说明、下次课程计划或提醒。",
        tutorial_preview_game_title = "预览游戏",
        tutorial_preview_game_text = "点击“预览游戏”在学生游玩前进行测试。",
        tutorial_preview_success_title = "预览成功消息",
        tutorial_preview_success_text = "点击“预览成功消息”查看学生完成后将收到的消息。",
        tutorial_sample_level_name = "初学者 - 诗篇 118:1",
        tutorial_sample_theme = "海底世界 ▼",
        tutorial_sample_words = "神是美善的",
        tutorial_sample_success_message = "做得很好！本周请记住这节经文。",
        preview_game    = "预览游戏",
        preview_success = "预览成功信息",
        edit_level = "编辑关卡",
        save_first = "请先保存",
        theme_helper = "为此关卡选择一个主题。",
        add_words_to_remember = "添加要记住的词语",
        add_success_message = "添加成功信息",
        new_code = "新代码",
        published = "已发布",
        draft = "草稿",
        loading_classes = "正在加载班级...",
        share_with_students = "把这个分享给你的学生。",
        enter_level_name = "输入关卡名称",
        save = "保存",
        tap_theme_then_done = "点击一个主题，然后点完成",
        selected_theme = "已选择",
        done = "完成",
        save_to_preview_edits = "保存后可预览编辑内容",
        missing_user_class = "缺少用户或班级。",
        please_enter_level_name = "请输入关卡名称。",
        creating_new_level = "正在创建新关卡...",
        hint_instruction = "按顺序接住单词。",
        hint_remove_last_word = "接住%s来删除最后一个词。",
        hint_tap_panel = "点击此面板查看经文。",
        missing_level_id = "缺少关卡 ID。",
        please_select_level_first = "请先选择一个关卡。",
        deleting = "正在删除",
        delete_failed = "删除失败。",
        needs_text = "缺少文本",
        delete_level = "删除关卡？",
        delete_level_msg = "这将删除此关卡。",
        delete = "删除",
        dont_see_level = "没看到你想要的关卡？在下面添加一个。",
        add_level = "添加关卡",
        manage = "管理",
        no_success_messages_found = "未找到成功消息",
        loaded = "已加载",
        title_topic_or_passage = "标题、主题或段落",
        add_new = "新增",
        select_class = "选择你的班级",
        select_label = "选择班级",
        no_class_selected = "未选择班级",
        no_classes_available = "没有可用班级",
        add_class = "添加班级",
        save_class = "保存班级",
        load_class = "正在加载班级",
        load_failed = "加载失败",
        load_error = "加载错误",
        loading = "正在加载...",
        please_select_class = "请先选择一个班级，然后再继续。",
        ok = "确定",
        class_id = "班级编号",
        class_name = "输入班级名称",
        error_missing = "请输入班级编号和班级名称。",
        success_added = "班级已添加！",
        error_connection = "无法连接到服务器，请稍后再试。",
        next = "下一步",
        back = "返回",
        select_language = "选择语言",
        language_updated = "语言已更新",
        restart_notice = "更改将立即生效。",
        play_game = "开始游戏",
        create = "创建",
        enter_code = "输入代码",
        hint = "提示",
        please_enter_class_code = "请输入班级代码。",
        please_login = "请登录。",
        please_login_or_enter_class_code = "请登录或输入班级代码。",
        welcome = "欢迎",
        welcome_to = "欢迎来到",
        theme = "主题",
        about    = "关于",  
        support  = "支持",
        settings = "设置",
       optional_add_class = "可选：添加新班级",
        picker_hint = "滚动选择一个班级，然后点击进行选择。",

        select = "选择",
        -- Add or Select Class
        select_your_class = "添加或选择班级",                             -- zh

        cancel = "取消",
        dont_see_class = "找不到你的班级？在下面添加一个。",
        class_name_label = "班级名称",
        add_one_below = "在下面添加一个。",

        words_to_remember = "要记住的词语",
        words_to_remember_help = "学习者在游戏中要抓住的词语。",
        success_message = "成功信息",

        saving_success   = "正在保存成功信息...",
        updating_success = "正在更新成功信息...",
        success_saved    = "成功信息已保存！",
        success_updated  = "成功信息已更新！",
        success_message_help = "在学习者完成游戏后显示。",

        you_completed = "你已完成",
        you_completed_level               = "你已完成关卡",
        loading_success_message           = "正在加载成功信息",
        loading_success_message_for_level = "正在加载该关卡的成功信息",
    
        version = "版本",
        contact_support = "联系支持",
        kids_privacy = "隐私政策",
        visit_website = "使用条款",

        choose_level = "选择关卡",
        select_level = "选择关卡",
        no_levels_found = "未找到关卡",
        find_class = "查找班级",
        class_code = "班级代码",
        dont_have_code = "没有代码？",
        use_demo_code  = "使用 12345 立即开始游戏！",
        get_code_from_teacher = "向你的老师获取代码。",
        about_smartsheep = "关于 SmartSheep",
                too_long = "太长了",
        verse_too_long = "经文太长了",
        success_too_long = "成功消息太长了",

        class_name_required = "班级名称为必填项",
        missing_user = "未找到用户",
        missing_prefix = "缺少前缀",
        saved = "已保存",
        levels = "关卡",

        log_out = "退出登录",
        subscribe = "订阅",
        sign_up = "注册",
        create_classes = "为你的学生创建班级和有趣的关卡",

        paywall_title = "1个月免费试用",
        paywall_price_default = "首月免费，之后...",
        paywall_price_template = "首月免费，之后 %s/月",
        paywall_cancel_anytime = "可随时通过 Google Play 取消",
        paywall_benefit = "可创建并更新无限数量的班级和关卡",

        paywall_start_trial = "开始免费试用",
        paywall_restore_purchases = "恢复购买",

        paywall_loading_price = "正在加载价格...",
        paywall_loading_google_play_price = "正在从 Google Play 加载价格...",

        paywall_status_active = "高级版已激活。",
        paywall_status_verify_failed = "无法验证订阅状态。",
        paywall_status_login_first = "请先登录。",
        paywall_status_loading_google_play = "订阅信息仍在从 Google Play 加载中...",
        paywall_status_product_missing_google_play = "在 Google Play 中未找到订阅产品。",
        paywall_status_opening_checkout = "正在打开安全的 Google Play 结账页面...",
        paywall_status_purchase_cancelled = "购买已取消。",
        paywall_status_purchase_failed = "购买失败。",
        paywall_status_purchase_failed_with_error = "购买失败：%s",

        paywall_status_verified = "高级版已激活。订阅已验证。",
        paywall_status_checking = "正在检查订阅状态...",
        paywall_status_restored = "高级版已激活。订阅已恢复。",
        paywall_status_not_found = "未找到有效订阅。",
        paywall_status_restore_failed_with_error = "无法恢复订阅：%s",
        paywall_status_product_not_found_short = "未找到产品。",
        paywall_status_google_play_details_failed = "无法加载 Google Play 产品详情。",
        about_body =
    "SmartSheep 将圣经背诵变成一个有趣的游戏。\n\n" ..
    "一次捕捉一个词，直到经文被完整、准确地完成。\n\n" ..
    "专为家庭、课堂和事工而设计。",
        eraser_coconut = "椰子",
        eraser_banana  = "香蕉",
        eraser_leaf    = "叶子",
        eraser_sprig   = "嫩枝",
        eraser_flower  = "花",
        eraser_fish    = "鱼",

    },

    ----------------------------------------------------------------
    -- Japanese
    ----------------------------------------------------------------
    ja = {
        home = "ホーム",
        edit = "編集",
        greeting = "こんにちは",
        game_catch = "キャッチ",
        game_catch_desc = "単語をキャッチ",

        game_match = "マッチ",
        game_match_desc = "単語をドラッグ",
        word_card_game = "単語カードゲーム",
        drag_words_instruction = "単語カードを正しい場所にドラッグしましょう。",
        screen_count = "%d / %d 画面",
        no_words_saved = "まず単語を追加してから、ゲームをプレビューしてください。",

        game_order = "順番",
        game_order_desc = "正しい順番につなぐ",
        line_match_game = "ラインマッチゲーム",
        draw_line_instruction = "各単語から対応する場所へ線を引きましょう。",
        player = "プレイヤー",
        menu = "メニュー",
        choose_a_game = "ゲームを選択",
        log_in = "ログイン",
        exit = "終了",
        language = "言語",
        success = "成功",
        error = "エラー",
        saving = "保存中...",
        save_failed = "保存に失敗しました",
        updated = "更新されました",
        updating = "更新中...",
        seed_error = "シードエラー",
        no_passages_found = "パッセージが見つかりません",
        creating_new_passage = "新しいパッセージを作成中...",
        select_passage  = "編集するパッセージを選択",
        tutorial_welcome_title = "ようこそ！",
        tutorial_welcome_text = "生徒のために楽しい聖書ゲームを作りましょう。生徒はあなたが作った内容で遊びます。",
        tutorial_students_play_title = "生徒が遊ぶ",
        tutorial_students_play_text = "あなたのクラスとレベルが、生徒向けのゲームになります。",
        tutorial_student_app_text = "生徒は SmartSheep 生徒用アプリをインストールします。無料で、広告はありません。",
        tutorial_add_class_title = "クラスを追加",
        tutorial_add_class_text = "下の「クラスを追加」をタップして、最初のクラスを作成してください。",
        tutorial_class_details_title = "クラスの詳細",
        tutorial_class_details_text = "生徒は生成された ID を使ってあなたのゲームにアクセスします。",
        tutorial_students_join_title = "生徒が参加",
        tutorial_students_join_text = "SmartSheep アプリで、生徒はあなたのクラス ID を入力します。",
        tutorial_students_replay_text = "参加後、生徒はアプリ内であなたのクラスを見つけ、何度でも遊べます。",
        tutorial_tutorials_title = "チュートリアル",
        tutorial_tutorials_text = "各画面の右上にある ? からチュートリアルを確認できます。",
        tutorial_catch_words = "言葉をキャッチ！",
        tutorial_next = "次へ ›",

        tutorial_class_settings_title = "クラス設定",
        tutorial_class_settings_text = "ここでクラス情報を更新できます。",
        tutorial_change_class_name_title = "クラス名を変更",
        tutorial_change_class_name_text = "クラス名の欄をタップして名前を変更します。",
        tutorial_publish_class_title = "クラスを公開",
        tutorial_publish_class_text = "生徒向けの準備ができたら「公開」をタップします。",
        tutorial_save_changes_title = "変更を保存",
        tutorial_save_changes_text = "保存をタップして、クラス名と公開設定を更新します。",
        tutorial_add_level_title = "レベルを追加",
        tutorial_add_level_text = "レベルを追加をタップして、このクラス用のゲームレベルを作成します。",
        tutorial_class_name_label = "クラス名：",
        tutorial_sample_class_name = "日曜学校",
        tutorial_draft = "下書き",
        tutorial_published = "公開済み",
        tutorial_add_level_button = "➕ レベルを追加",

        tutorial_level_title_title = "レベルタイトル",
        tutorial_level_title_text = "レベルにタイトルを付けましょう。生徒は遊ぶ内容を選ぶときにこのタイトルを見ます。",
        tutorial_choose_theme_title = "テーマを選択",
        tutorial_choose_theme_text = "テーマを選んでゲームの見た目を変更します。",
        tutorial_words_to_remember_title = "覚える言葉",
        tutorial_words_to_remember_text = "暗記する聖句や、生徒に覚えてほしい言葉を追加します。",
        tutorial_success_message_title = "成功メッセージ",
        tutorial_success_message_text = "励ましの言葉、聖句の説明、次回のクラス予定、またはリマインダーを追加します。",
        tutorial_preview_game_title = "ゲームをプレビュー",
        tutorial_preview_game_text = "生徒が遊ぶ前に「ゲームをプレビュー」をタップしてテストします。",
        tutorial_preview_success_title = "成功メッセージをプレビュー",
        tutorial_preview_success_text = "完了後に生徒へ表示されるメッセージを確認するには「成功メッセージをプレビュー」をタップします。",
        tutorial_sample_level_name = "初級クラス - 詩篇 118:1",
        tutorial_sample_theme = "海の中 ▼",
        tutorial_sample_words = "神は良いお方です",
        tutorial_sample_success_message = "よくできました！今週はこの聖句を覚えておきましょう。",
        preview_game    = "ゲームをプレビュー",
        preview_success = "成功メッセージをプレビュー",
        edit_level = "レベルを編集",
        save_first = "先に保存してください",
        theme_helper = "このレベルのテーマを選択してください。",
        add_words_to_remember = "覚える言葉を追加",
        add_success_message = "成功メッセージを追加",
        new_code = "新しいコード",
        published = "公開済み",
        draft = "下書き",
        loading_classes = "クラスを読み込み中...",
        share_with_students = "これを生徒に共有してください。",
        enter_level_name = "レベル名を入力",
        save = "保存",
        tap_theme_then_done = "テーマをタップしてから完了を押してください",
        selected_theme = "選択中",
        done = "完了",
        save_to_preview_edits = "編集内容をプレビューするには保存してください",
        missing_user_class = "ユーザーまたはクラスがありません。",
        please_enter_level_name = "レベル名を入力してください。",
        creating_new_level = "新しいレベルを作成中...",
        hint_instruction = "言葉を順番に集めましょう。",
        hint_remove_last_word = "%sをキャッチして最後の言葉を消しましょう。",
        hint_tap_panel = "このパネルをタップして聖書箇所を表示します。",
        missing_level_id = "レベルIDがありません。",
        please_select_level_first = "先にレベルを選択してください。",
        deleting = "削除中",
        delete_failed = "削除に失敗しました。",
        needs_text = "テキストが必要です",
        delete_level = "レベルを削除しますか？",
        delete_level_msg = "このレベルは削除されます。",
        delete = "削除",
        dont_see_level = "ほしいレベルが見つかりませんか？下に追加してください。",
        add_level = "レベルを追加",
        manage = "管理",
        no_success_messages_found = "成功メッセージが見つかりませんでした",
        loaded = "読み込み完了",
        title_topic_or_passage = "タイトル、トピックまたはパッセージ",
        add_new = "新規追加",
        select_class = "クラスを選択してください",
        select_label = "クラスを選択",
        no_class_selected = "クラスが選択されていません",
        no_classes_available = "利用可能なクラスがありません",
        add_class = "クラスを追加",
        save_class = "クラスを保存",
        load_class = "クラスを読み込み中",
        load_failed = "読み込みに失敗しました",
        load_error = "読み込みエラー",
        loading = "読み込み中...",
        please_select_class = "続行する前にクラスを選択してください。",
        ok = "OK",
        class_id = "クラスID",
        class_name = "クラス名を入力",
        error_missing = "クラスIDとクラス名の両方を入力してください。",
        success_added = "クラスが追加されました！",
        error_connection = "サーバーに接続できません。後でもう一度お試しください。",
        next = "次へ",
        back = "戻る",
        select_language = "言語を選択",
        language_updated = "言語が更新されました",
        restart_notice = "変更はすぐに適用されます。",
        play_game = "ゲームをプレイ",
        create = "作成",
        enter_code = "コードを入力",
        hint = "ヒント",
        please_enter_class_code = "クラスコードを入力してください。",
        please_login = "ログインしてください。",
        please_login_or_enter_class_code = "ログインするかクラスコードを入力してください。",
        welcome = "ようこそ",
        welcome_to = "ようこそ ",
        theme = "テーマ",
        about    = "情報",
        support  = "サポート",
        settings = "設定",
        optional_add_class = "任意：新しいクラスを追加",
        picker_hint = "スクロールしてクラスを選び、タップして選択してください。",
        select = "選択",
        -- Add or Select Class
        select_your_class = "クラスを追加または選択",                      -- ja

        cancel = "キャンセル",
        dont_see_class = "クラスが見つかりませんか？下に追加してください。",
        class_name_label = "クラス名",
        add_one_below = "下に追加してください。",

        words_to_remember = "覚える言葉",
        words_to_remember_help = "ゲーム中に学習者がつかまえる言葉です。",
        success_message = "成功メッセージ",

        saving_success   = "成功メッセージを保存中...",
        updating_success = "成功メッセージを更新中...",
        success_saved    = "成功メッセージが保存されました！",
        success_updated  = "成功メッセージが更新されました！",
        success_message_help = "学習者がゲームを完了した後に表示されます。",

        you_completed = "完了しました",
        you_completed_level               = "レベルをクリアしました",
        loading_success_message           = "成功メッセージを読み込み中",
        loading_success_message_for_level = "このレベルの成功メッセージを読み込み中",

        version = "バージョン",
        contact_support = "サポートに連絡",
        kids_privacy = "プライバシーポリシー",
        visit_website = "利用規約",

        choose_level = "レベルを選択",
        select_level = "レベルを選択",
        no_levels_found = "レベルが見つかりません",
        find_class = "クラスを探す",
        class_code = "クラスコード",
        dont_have_code = "コードがありませんか？",
        use_demo_code  = "12345 を使って今すぐ遊ぼう！",
        get_code_from_teacher = "先生からコードをもらってください。",
        about_smartsheep = "SmartSheep について",
                too_long = "長すぎます",
        verse_too_long = "聖句が長すぎます",
        success_too_long = "成功メッセージが長すぎます",

        class_name_required = "クラス名は必須です",
        missing_user = "ユーザーが見つかりません",
        missing_prefix = "プレフィックスがありません",
        saved = "保存しました",
        levels = "レベル",

        log_out = "ログアウト",
        subscribe = "登録する",
        sign_up = "サインアップ",
        create_classes = "生徒のためにクラスと楽しいレベルを作成しましょう",

        paywall_title = "1か月無料トライアル",
        paywall_price_default = "1か月無料、その後...",
        paywall_price_template = "1か月無料、その後 %s/月",
        paywall_cancel_anytime = "Google Play からいつでもキャンセルできます",
        paywall_benefit = "クラスとレベルを無制限に作成・更新できます",

        paywall_start_trial = "無料トライアルを開始",
        paywall_restore_purchases = "購入を復元",

        paywall_loading_price = "価格を読み込み中...",
        paywall_loading_google_play_price = "Google Play から価格を読み込み中...",

        paywall_status_active = "プレミアムが有効です。",
        paywall_status_verify_failed = "サブスクリプションの状態を確認できませんでした。",
        paywall_status_login_first = "先にログインしてください。",
        paywall_status_loading_google_play = "サブスクリプション情報を Google Play から読み込み中です...",
        paywall_status_product_missing_google_play = "Google Play でサブスクリプション商品が見つかりません。",
        paywall_status_opening_checkout = "安全な Google Play 購入画面を開いています...",
        paywall_status_purchase_cancelled = "購入がキャンセルされました。",
        paywall_status_purchase_failed = "購入に失敗しました。",
        paywall_status_purchase_failed_with_error = "購入に失敗しました: %s",

        paywall_status_verified = "プレミアムが有効です。サブスクリプションを確認しました。",
        paywall_status_checking = "サブスクリプションの状態を確認中...",
        paywall_status_restored = "プレミアムが有効です。サブスクリプションを復元しました。",
        paywall_status_not_found = "有効なサブスクリプションが見つかりません。",
        paywall_status_restore_failed_with_error = "サブスクリプションを復元できませんでした: %s",
        paywall_status_product_not_found_short = "商品が見つかりません。",
        paywall_status_google_play_details_failed = "Google Play の商品詳細を読み込めませんでした。",
        about_body =
    "SmartSheep は、聖書暗記を楽しいゲームに変えます。\n\n" ..
    "一語ずつキャッチして、正確に聖句を完成させましょう。\n\n" ..
    "家族、クラス、ミニストリーのために作られました。",
        eraser_coconut = "ココナッツ",
        eraser_banana  = "バナナ",
        eraser_leaf    = "葉",
        eraser_sprig   = "小枝",
        eraser_flower  = "花",
        eraser_fish    = "魚",

    },

    ----------------------------------------------------------------
    -- Korean
    ----------------------------------------------------------------
    ko = {
        home = "홈",
        edit = "편집",
        greeting = "안녕하세요",
        game_catch = "잡기",
        game_catch_desc = "단어를 잡으세요",
        game_match = "짝맞추기",
        game_match_desc = "단어를 드래그하세요",
        word_card_game = "단어 카드 게임",
        drag_words_instruction = "각 단어 카드를 올바른 위치로 드래그하세요.",
        screen_count = "%d / %d 화면",
        no_words_saved = "먼저 단어를 추가한 다음 게임을 미리 보세요.",
        game_order = "순서",
        game_order_desc = "올바른 순서 연결",
        line_match_game = "선 연결 게임",
        draw_line_instruction = "각 단어에서 알맞은 위치까지 선을 그으세요.",
        player = "플레이어",
        menu = "메뉴",
        choose_a_game = "게임 선택",
        log_in = "로그인",
        exit = "종료",
        language = "언어",
        success = "성공",
        error = "오류",
        saving = "저장 중...",
        save_failed = "저장 실패",
        updated = "업데이트됨",
        updating = "업데이트 중...",
        seed_error = "시드 오류",
        no_passages_found = "구절을 찾을 수 없습니다",
        creating_new_passage = "새 구절을 만드는 중...",
        select_passage  = "편집할 구절 선택",
        tutorial_welcome_title = "환영합니다!",
        tutorial_welcome_text = "학생들을 위한 재미있는 성경 게임을 만드세요. 학생들은 선생님이 만든 내용을 플레이합니다.",
        tutorial_students_play_title = "학생들이 플레이",
        tutorial_students_play_text = "선생님의 클래스와 레벨이 학생들을 위한 게임이 됩니다.",
        tutorial_student_app_text = "학생들은 SmartSheep 학생용 앱을 설치합니다. 무료이며 광고가 없습니다.",
        tutorial_add_class_title = "클래스 추가",
        tutorial_add_class_text = "아래의 클래스 추가를 눌러 첫 클래스를 만드세요.",
        tutorial_class_details_title = "클래스 세부 정보",
        tutorial_class_details_text = "학생들은 생성된 ID로 선생님의 게임에 접속합니다.",
        tutorial_students_join_title = "학생 참여",
        tutorial_students_join_text = "SmartSheep 앱에서 학생들은 선생님의 클래스 ID를 입력합니다.",
        tutorial_students_replay_text = "참여 후 학생들은 앱에서 선생님의 클래스를 보고 반복해서 플레이할 수 있습니다.",
        tutorial_tutorials_title = "튜토리얼",
        tutorial_tutorials_text = "각 화면 오른쪽 위의 ? 아래에서 튜토리얼을 확인하세요.",
        tutorial_catch_words = "단어를 잡으세요!",
        tutorial_next = "다음 ›",

        tutorial_class_settings_title = "클래스 설정",
        tutorial_class_settings_text = "여기에서 클래스 정보를 수정할 수 있습니다.",
        tutorial_change_class_name_title = "클래스 이름 변경",
        tutorial_change_class_name_text = "클래스 이름 상자를 눌러 이름을 변경하세요.",
        tutorial_publish_class_title = "클래스 게시",
        tutorial_publish_class_text = "학생들이 사용할 준비가 되면 게시됨을 누르세요.",
        tutorial_save_changes_title = "변경 사항 저장",
        tutorial_save_changes_text = "저장을 눌러 클래스 이름과 게시 설정을 업데이트하세요.",
        tutorial_add_level_title = "레벨 추가",
        tutorial_add_level_text = "레벨 추가를 눌러 이 클래스용 게임 레벨을 만드세요.",
        tutorial_class_name_label = "클래스 이름:",
        tutorial_sample_class_name = "주일학교",
        tutorial_draft = "초안",
        tutorial_published = "게시됨",
        tutorial_add_level_button = "➕ 레벨 추가",

        tutorial_level_title_title = "레벨 제목",
        tutorial_level_title_text = "레벨에 제목을 지정하세요. 학생들은 플레이할 항목을 선택할 때 이 제목을 보게 됩니다.",
        tutorial_choose_theme_title = "테마 선택",
        tutorial_choose_theme_text = "게임의 모양을 변경할 테마를 선택하세요.",
        tutorial_words_to_remember_title = "기억할 말씀",
        tutorial_words_to_remember_text = "학생들이 기억하기를 원하는 성경 구절이나 단어를 추가하세요.",
        tutorial_success_message_title = "성공 메시지",
        tutorial_success_message_text = "격려의 말, 성경 구절 설명, 다음 수업 계획 또는 알림을 추가하세요.",
        tutorial_preview_game_title = "게임 미리보기",
        tutorial_preview_game_text = "학생들이 플레이하기 전에 게임 미리보기를 눌러 테스트하세요.",
        tutorial_preview_success_title = "성공 메시지 미리보기",
        tutorial_preview_success_text = "학생들이 완료 후 받게 될 메시지를 보려면 성공 메시지 미리보기를 누르세요.",
        tutorial_sample_level_name = "초급반 - 시편 118:1",
        tutorial_sample_theme = "바닷속 ▼",
        tutorial_sample_words = "하나님은 선하십니다",
        tutorial_sample_success_message = "잘했습니다! 이번 주에는 이 구절을 기억해 보세요.",
        preview_game    = "게임 미리보기",
        preview_success = "성공 메시지 미리보기",
        edit_level = "레벨 편집",
        save_first = "먼저 저장하세요",
        theme_helper = "이 레벨의 테마를 선택하세요.",
        add_words_to_remember = "기억할 단어 추가",
        add_success_message = "성공 메시지 추가",
        new_code = "새 코드",
        published = "게시됨",
        draft = "초안",
        loading_classes = "클래스를 불러오는 중...",
        share_with_students = "이것을 학생들과 공유하세요.",
        enter_level_name = "레벨 이름을 입력하세요",
        save = "저장",
        tap_theme_then_done = "테마를 탭한 다음 완료를 누르세요",
        selected_theme = "선택됨",
        done = "완료",
        save_to_preview_edits = "수정 내용을 미리 보려면 저장하세요",
        missing_user_class = "사용자 또는 클래스가 없습니다.",
        please_enter_level_name = "레벨 이름을 입력하세요.",
        creating_new_level = "새 레벨을 만드는 중...",
        hint_instruction = "단어를 순서대로 모으세요.",
        hint_remove_last_word = "%s을(를) 잡아 마지막 단어를 지우세요.",
        hint_tap_panel = "이 패널을 눌러 성경 구절을 확인하세요.",
        missing_level_id = "레벨 ID가 없습니다.",
        please_select_level_first = "먼저 레벨을 선택하세요.",
        deleting = "삭제 중",
        delete_failed = "삭제하지 못했습니다.",
        needs_text = "텍스트 필요",
        delete_level = "레벨을 삭제할까요?",
        delete_level_msg = "이 레벨이 삭제됩니다.",
        delete = "삭제",
        dont_see_level = "원하는 레벨이 없나요? 아래에서 추가하세요.",
        add_level = "레벨 추가",
        manage = "관리",
        no_success_messages_found = "성공 메시지를 찾을 수 없습니다",
        loaded = "불러옴",
        title_topic_or_passage = "제목, 주제 또는 구절",
        add_new = "새로 추가",
        select_class = "클래스를 선택하세요",
        select_label = "클래스 선택",
        no_class_selected = "선택된 클래스가 없습니다",
        no_classes_available = "사용 가능한 클래스가 없습니다",
        add_class = "클래스 추가",
        save_class = "클래스 저장",
        load_class = "클래스 불러오는 중",
        load_failed = "불러오기 실패",
        load_error = "로드 오류",
        loading = "로딩 중...",
        please_select_class = "계속하기 전에 클래스를 선택하세요.",
        ok = "확인",
        class_id = "클래스 ID",
        class_name = "클래스 이름 입력",
        error_missing = "클래스 ID와 이름을 모두 입력하세요.",
        success_added = "클래스가 추가되었습니다!",
        error_connection = "서버에 연결할 수 없습니다. 나중에 다시 시도해주세요.",
        next = "다음",
        back = "뒤로",
        select_language = "언어 선택",
        language_updated = "언어가 업데이트되었습니다",
        restart_notice = "변경 사항이 즉시 적용됩니다.",
        play_game = "게임하기",
        create = "생성",
        enter_code = "코드 입력",
        hint = "힌트",
        please_enter_class_code = "클래스 코드를 입력하세요.",
        please_login = "로그인하세요.",
        please_login_or_enter_class_code = "로그인하거나 클래스 코드를 입력하세요.",
        welcome = "환영합니다",
        welcome_to = "환영합니다 ",
        theme = "테마",
        about    = "정보",
        support  = "지원",
        settings = "설정",
        optional_add_class = "선택 사항: 새 클래스 추가",
        picker_hint = "스크롤하여 클래스를 선택한 다음 탭하여 선택하세요.",
        select = "선택",
        -- Add or Select Class
        select_your_class = "클래스 추가 또는 선택",                        -- ko

        cancel = "취소",
        dont_see_class = "클래스가 보이지 않나요? 아래에서 추가하세요.",
        class_name_label = "클래스 이름",
        add_one_below = "아래에서 추가하세요.",

        words_to_remember = "기억할 단어",
        words_to_remember_help = "학습자가 게임에서 잡을 단어들입니다.",
        success_message = "성공 메시지",

        saving_success   = "성공 메시지를 저장 중...",
        updating_success = "성공 메시지를 업데이트 중...",
        success_saved    = "성공 메시지가 저장되었습니다!",
        success_updated  = "성공 메시지가 업데이트되었습니다!",
        success_message_help = "학습자가 게임을 완료하면 표시됩니다.",
        
        you_completed = "완료했습니다",
        you_completed_level               = "레벨을 완료했습니다",
        loading_success_message           = "성공 메시지를 불러오는 중",
        loading_success_message_for_level = "해당 레벨의 성공 메시지를 불러오는 중",
    
        version = "버전",
        contact_support = "고객 지원 문의",
        kids_privacy = "개인정보 처리방침",
        visit_website = "이용 약관",

        choose_level = "레벨 선택",
        select_level = "레벨 선택",
        no_levels_found = "레벨을 찾을 수 없습니다",
        find_class = "클래스 찾기",
        class_code = "클래스 코드",
        dont_have_code = "코드가 없나요?",
        use_demo_code  = "12345를 사용해 지금 바로 플레이하세요!",
        get_code_from_teacher = "선생님에게서 코드를 받으세요.",
        about_smartsheep = "SmartSheep 정보",
                too_long = "너무 깁니다",
        verse_too_long = "구절이 너무 깁니다",
        success_too_long = "성공 메시지가 너무 깁니다",

        class_name_required = "클래스 이름이 필요합니다",
        missing_user = "사용자를 찾을 수 없습니다",
        missing_prefix = "접두사가 없습니다",
        saved = "저장됨",
        levels = "레벨",

        log_out = "로그아웃",
        subscribe = "구독",
        sign_up = "가입하기",
        create_classes = "학생들을 위한 클래스와 재미있는 레벨을 만드세요",

        paywall_title = "1개월 무료 체험",
        paywall_price_default = "1개월 무료, 이후...",
        paywall_price_template = "1개월 무료, 이후 월 %s",
        paywall_cancel_anytime = "Google Play에서 언제든지 취소할 수 있습니다",
        paywall_benefit = "무제한 클래스와 레벨을 만들고 업데이트할 수 있습니다",

        paywall_start_trial = "무료 체험 시작",
        paywall_restore_purchases = "구매 복원",

        paywall_loading_price = "가격을 불러오는 중...",
        paywall_loading_google_play_price = "Google Play에서 가격을 불러오는 중...",

        paywall_status_active = "프리미엄이 활성화되었습니다.",
        paywall_status_verify_failed = "구독 상태를 확인할 수 없습니다.",
        paywall_status_login_first = "먼저 로그인하세요.",
        paywall_status_loading_google_play = "Google Play에서 구독 정보를 아직 불러오는 중입니다...",
        paywall_status_product_missing_google_play = "Google Play에서 구독 상품을 찾을 수 없습니다.",
        paywall_status_opening_checkout = "안전한 Google Play 결제를 여는 중입니다...",
        paywall_status_purchase_cancelled = "구매가 취소되었습니다.",
        paywall_status_purchase_failed = "구매에 실패했습니다.",
        paywall_status_purchase_failed_with_error = "구매에 실패했습니다: %s",

        paywall_status_verified = "프리미엄이 활성화되었습니다. 구독이 확인되었습니다.",
        paywall_status_checking = "구독 상태를 확인하는 중...",
        paywall_status_restored = "프리미엄이 활성화되었습니다. 구독이 복원되었습니다.",
        paywall_status_not_found = "활성 구독을 찾을 수 없습니다.",
        paywall_status_restore_failed_with_error = "구독을 복원할 수 없습니다: %s",
        paywall_status_product_not_found_short = "상품을 찾을 수 없습니다.",
        paywall_status_google_play_details_failed = "Google Play 상품 세부정보를 불러올 수 없습니다.",
        about_body =
    "SmartSheep은 성경 암송을 재미있는 게임으로 바꿉니다.\n\n" ..
    "한 단어씩 잡아 정확하게 구절을 완성하세요.\n\n" ..
    "가족, 수업, 사역을 위해 만들어졌습니다.",
        eraser_coconut = "코코넛",
        eraser_banana  = "바나나",
        eraser_leaf    = "잎",
        eraser_sprig   = "잔가지",
        eraser_flower  = "꽃",
        eraser_fish    = "물고기",

    },
}

------------------------------------------------------------
-- Public functions
------------------------------------------------------------
function M.setLanguage(lang)
    -- Guard: if lang is not supported, fall back to English
    if not (lang and M.text[lang]) then
        lang = "en"
    end

    M.current = lang

    -- Persist selection so it can be read on next launch
    system.setPreferences("app", { language = lang })
end

function M.t(key)
    -- 1) Try current language
    -- 2) Fallback to English
    -- 3) Fallback to key name
    return (M.text[M.current] and M.text[M.current][key])
        or (M.text["en"] and M.text["en"][key])
        or key
end

return M
